### ISSUE TITLE
Greater control over 3rd party requests

### ISSUE THREAD

**Issue by orbisvicis** [muzuiget/referrer_control#24]
By having "Ignore same domains request" as a global settings, you loose much of the functionality provided by the alternative addon, [RefControl](https://addons.mozilla.org/en-US/firefox/addon/refcontrol/). I also find treating the default rule as any other rule more intuitive and logical.

I wrote a [review at this addon's firefox page](https://addons.mozilla.org/en-US/firefox/addon/referrer-control/reviews/592626/) detailing the problem. Yep, that's me, just didn't know which site you prefer checking.

**Comment by muzuiget** [comment]
Firefox has drop support XUL in the future, I lost interesting to use XUL, no new feature, just bugfix.
