### ISSUE TITLE
When addon switched off, icon does not displayed in last Nightly

### ISSUE THREAD

**Issue by Halibut80** [muzuiget/referrer_control#30]
<img src="http://lh5.ggpht.com/-jvI7jJTAB2Q/VEF_gTMC3AI/AAAAAAAAZ9Q/2A71t8n_XYM/s0/screenshot%2525202014-10-18%252520002.png" border=0><br/>&nbsp;<br/>
Win 8.1 x64, Firefox Nightly 36.0a1, BuildID: 20141017030201

**Comment by muzuiget** [comment]
Should be fixed in `v0.5.0`
