### ISSUE TITLE
Order of dropdown items can be improved

### ISSUE THREAD

**Issue by Gitoffthelawn** [muzuiget/referrer_control#32]
The order of the dropdown items can be changed to make it easier to understand.

The current order is 'skip, remove, source host, source domain, target host, target domain, target url'.
As you progress on the list, in some cases, it gets more specific, and in some cases, it gets less specific.
I recommend changing it to: 'skip, remove, source domain, source host, target domain, target host, target url'.
This way, it always gets more specific as you go down the list.

**Comment by muzuiget** [comment]
Because I treat "domain" as a special case of "host", host includes IP and domain at first.

Your reason also make sense. But after looking the code, I decide keep it as is. My bad, I use the UI order as value, so change the order will break the user's config.

**Comment by Gitoffthelawn** [comment]
Makes sense.  You would have to recode a little or could just add a conversion line to convert the UI order to the code value.
