### ISSUE TITLE
Show the referer that the browser is sending

### ISSUE THREAD

**Issue by ReporterX** [muzuiget/referrer_control#35]
It would be great if there is an option to show the URL (referer) the browser is sending in the toolbar. Something like this:

![Display referer](http://snag.gy/u8jXT.jpg)

So I can see if the addon works as expected, or test to see if the entries I added are working properly.

**Comment by Gitoffthelawn** [comment]
+1

Or perhaps as a tooltip or an item in the drop-down menu.

**Comment by muzuiget** [comment]
We can't do this, because one page can send lot of request, But you can check them in Firefox DevTools "Network" panel.

**Comment by Gitoffthelawn** [comment]
It could be done for the destination page.  IOW, show the referer sent for the current page.  There was an extension that did this in the statusbar... back when the statusbar still existed.

For example, if you are on `foobar.com`, and you came from `muzuiget.com` (without any referer blocking or spoofing), it would show `muzuiget.com`.
