### ISSUE TITLE
Column width adjustments

### ISSUE THREAD

**Issue by Gitoffthelawn** [muzuiget/referrer_control#39]
In the `Rule Preferences` dialog box, it would be useful if the first two columns were wider, and the last column narrower.

**Comment by muzuiget** [comment]
You can drag to resize it?

**Comment by Gitoffthelawn** [comment]
I'll give it a try in v0.5.0 when it hits AMO.  You might have to ping me then.

**Comment by muzuiget** [comment]
I add Travis-CI to build xpi file now, you can test it in [Release Page](https://github.com/muzuiget/referrer_control/releases), the same file I upload to AMO.

**Comment by muzuiget** [comment]
Any reponse?

**Comment by Gitoffthelawn** [comment]
Sorry for the delay.  I have now tested it.  The columns can be dragged, but the column widths are forgotten as soon as the window is closed.

Can defaults widths be adjusted to make the first two columns wider and the last column narrower?  Or is it possible to remember the column widths?
