### ISSUE TITLE
[ES6][ff-nightly] Convert const and let to var's (Bug 950547)

### ISSUE THREAD

**Issue by Halibut80** [muzuiget/referrer_control#41]
<a href="https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/">https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/</a>

**Comment by muzuiget** [comment]
I don't get it, `const` and `let` is ES6 standard, why should we convert it back to `var`?

**Comment by Halibut80** [comment]
@muzuiget, I dont know. :) But, without replacing const and let to var, "Referrer Control" and "User Agent Overrider", not work in latest Nightly's. More explanations can be found here: <a href="https://groups.google.com/forum/#!topic/mozilla.dev.platform/XoW35OxqDYI">Changes in chrome JS code due to ES6 global lexical scope</a> and <a href="https://bugzilla.mozilla.org/showdependencytree.cgi?id=950547&hide_resolved=0">https://bugzilla.mozilla.org/showdependencytree.cgi?id=950547&hide_resolved=0</a>

**Comment by muzuiget** [comment]
All right, I get it. I will take some time to fix this.
