### ISSUE TITLE
Target matching not working

### ISSUE THREAD

**Issue by pvalsecc** [muzuiget/referrer_control#42]
In my config I have:
- Ignore blank = true
- Ignore same domain = false
- Treat subdomains ... = false
- Default policy = Skip

I have only one rule:
- Source = http://localhost/pvalsecchi/theme/SBB
- Target = http://localhost/pvalsecchi/wsgi/mapserv_proxy?*
- Value = [Custom url] http://toto.com/xxx

I do some stuff on http://localhost/pvalsecchi/theme/SBB and apache outputs those two logs:
- 127.0.0.1 - - [02/Nov/2015:16:32:20 +0100] "GET **/pvalsecchi/mapserv**?LAYERS=bahnen%2Cdidok&STYLES=&WIDTH=2303&SERVICE=WMS&cache_version=4b92fe46201444f796b1867a4fcdfeee&FORMAT=image%2Fpng&REQUEST=GetMap&HEIGHT=753&SRS=EPSG%3A21781&VERSION=1.1.1&BBOX=472637.5%2C125925%2C587762.5%2C163575&TRANSPARENT=TRUE HTTP/1.1" 200 89500 "**http://toto.com/xxx**" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
- 127.0.0.1 - - [02/Nov/2015:16:32:20 +0100] "GET /pvalsecchi/wsgi/mapserv_proxy?cache_version=4b92fe46201444f796b1867a4fcdfeee&LAYERS=bahnen,didok&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A21781&BBOX=472637.5,125925,587762.5,163575&WIDTH=2303&HEIGHT=753 HTTP/1.1" 200 89592 "http://toto.com/xxx" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"

I don't understand why the first one has the referrer changed since the target URL doesn't match.

**Comment by pvalsecc** [comment]
I've tried with a regexp for the target and I same problem.

**Comment by muzuiget** [comment]
Should be fixed in `v0.5.0`, if still has any buy, please post a new issue.
