### ISSUE TITLE
Question mark characters must be escaped

### ISSUE THREAD

**Issue by Gitoffthelawn** [muzuiget/referrer_control#43]
If a wildcard (non-regex) rule contains a question mark, that character must be escaped with a backslash.

This needs to be changed, or documented.

The documentation only mentions asterisk being a wildcard character, but does not mention the question mark.

**Comment by Gitoffthelawn** [comment]
I updated the wiki to reflect the current design.

**Comment by muzuiget** [comment]
Can you create a PR? I move the docs to source repo now.

https://github.com/muzuiget/referrer_control/blob/master/docs/en-US/Usage.md
