### ISSUE TITLE
Custom Referer no longer working

### ISSUE THREAD

**Issue by Gitoffthelawn** [muzuiget/referrer_control#45]
Custom referers are no longer working.  Source and target referers work fine, but custom ones do no work.

Tested on Firefox 43.0.4

**Comment by 0xpr03** [comment]
It doesn't work anymore regardless the settings at FF 45.0.2

**Comment by muzuiget** [comment]
Should be fixed in `v0.5.0`, if still has any bug, please post a new issue.
