### ISSUE TITLE
This author already give up this referrer control extension

### ISSUE THREAD

**Issue by qmag** [muzuiget/referrer_control#49]
This author leaves that thing here very long time,it can not be used normally ,no update, not fix bugs anymore.
We should find another better extension

**Comment by Gitoffthelawn** [comment]
I was hoping you were mistaken, but at least for now, this extension does not work.  Hopefully the original author will fix it, or someone will fork it and get it working again.

**Comment by Gitoffthelawn** [comment]
@muzuiget Any possibility of fixing some bugs and also merging the pull requests?

**Comment by muzuiget** [comment]
Well, I will make it work again this weekend (July end), ping me here if I forget again. :smile:

**Comment by Gitoffthelawn** [comment]
@muzuiget Thanks so very much!

**Comment by Gitoffthelawn** [comment]
@muzuiget Ping :-) :heart:

**Comment by Gitoffthelawn** [comment]
@muzuiget Ping. Ping. :-) :-) :+1:

**Comment by muzuiget** [comment]
Fixed in `v0.5.0`

**Comment by Gitoffthelawn** [comment]
Thank you!

**Comment by Gitoffthelawn** [comment]
What are your thoughts on using the WebExtensions API for the next version?

**Comment by muzuiget** [comment]
No idea yet.
