### ISSUE TITLE
Make Referrer Control work on Firefox 44+ checklist

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/referrer_control#50]
What make Referrer Control broken since Firefox 44+ because there is a [breaking change on Firefox API ](https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/), some one have reported on issue #41. I just rename every `cosnt` and `let` back to `var`, then everything look right. But this is temporarily hack, the code should redactory to like my other extenstion [User Agent Overrrider](https://github.com/muzuiget/user_agent_overrider) later.

But there still "not working" issues unfixed. I need some ones to help re-test them if it work again after #41 is fixed. Testing by myself is too painful because hard to reproduce.
- [x] #45 
- [x] #42 
- [x] #38 

I add some code to help testing. Using Firefox addong debugging feature.
1. Download this source code, git clone or zip file.
2. Following the this [docs](about:debugging), when click the "Load Temporary Add-on", select the file `install.rdf`
3. Click the `Debug` in Referrer Control item list, an DevTools Console will openup.
4. Browser any page as usual, Referrer Control logging will show in DevTools Console

**Comment by Gitoffthelawn** [comment]
I didn't see this until now.  I'll take a look at it for you as soon as I can (might be several days... very busy).  Ping me if you don't hear back.

You might also want to update AMO with the above information and a link to this thread.

BTW, would it be easier for you to integrate User Agent Overrider and this extension into a single extension?

**Comment by muzuiget** [comment]
Firefox has drop support XUL in the future, I lost interesting to use XUL, just bugfix.

**Comment by Halibut80** [comment]
@muzuiget Please, fix also <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1222547">1222547 - Remove Array generics</a> for future.
