### ISSUE TITLE
Doesn't spoof document.referrer property

### ISSUE THREAD

**Issue by kirill9000** [muzuiget/referrer_control#53]

**Comment by muzuiget** [comment]
Because this just a HTTP Request spoofer.

**Comment by kirill9000** [comment]
Extension is advertised as a referrer spoofer, and this is an important bug. If you are unwilling to fix it, at least don't close the issue, so users would be informed about it.

BTW, [RefControl](https://addons.mozilla.org/en-US/firefox/addon/refcontrol/) does spoof `document.referrer`.
