### ISSUE TITLE
Spoofing referer on direct page visit?

### ISSUE THREAD

**Issue by reallyuniquename** [muzuiget/referrer_control#55]
I have set Referrer Control mode to "target url". 

If I visit `https://www.whatismyreferer.com/` page directly via URL bar there will be no referer in my HTTP request. I am not sure if this is intended. Is there any way to spoof referer header when browser sends none?

**Comment by muzuiget** [comment]
Please read https://github.com/muzuiget/referrer_control/blob/master/docs/en-US/Usage.md#blank-source

**Comment by reallyuniquename** [comment]
@muzuiget Oh, that's neat. Any chance to enable it on by-domain basis or have a quick way to enable/disable it?

**Comment by muzuiget** [comment]
You can use other extension to change `extensions.referrercontrol.ignoreBlankSource` item in `about:config`
