### ISSUE TITLE
Is addon broken?

### ISSUE THREAD

**Issue by Drugoy** [muzuiget/referrer_control#57]
I'd like to know the current state of the add-on.
My test shows that the add-on seems to not work.

STR:
0. Set referrer control to remove referrer.
1. VIsit http://i.imgur.com/2GklYkw.gifv
2. Open dev tools (F12) > Network and take a look at the request headers for each of the requested resource on that page - they all send referrers.

ReferrerControl 0.5.1, Firefox 54.0.1 x64, FreeBSD 11.0-RELEASE-p10.

**Comment by muzuiget** [comment]
Maybe you had check the "Ignore same domains request" option, read about on

https://github.com/muzuiget/referrer_control/tree/master/docs#same-domains

**Comment by Drugoy** [comment]
Thanks, that was it.
The option name got me confused.
